id: I3D2BF833
legacy_id: P008138
ocr_import_info:
  bdrc_scan_id: W1KG4218
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T04:56:33'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:24:48.861661+00:00'
last_modified: 2022-08-31 23:25:12.552208
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4218
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4218
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་ཐོར་བུ། དགེ་འདུན་ཆོས་སྐྱོང་རྒྱ་མཚོ།
  author: ཐར་ཤུལ ༠༤་དགེ་འདུན་ཆོས་སྐྱོང་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.5292233931047043
  ocr_word_median_confidence_index: 0.49000000953674316
quality: null
bases:
  I1PD97329:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD97329
      total_pages: 728
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD97329.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5292233931047043
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
