id: I3D2BF833
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T05:01:26+00:00'
last_modified: '2022-06-09T04:46:04.864421+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4218
  title: གསུང་ཐོར་བུ། དགེ་འདུན་ཆོས་སྐྱོང་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    AE74:
      image_group_id: I1PD97329
      title: Volume 1 of gsung thor bu/_dge 'dun chos skyong rgya mtsho
      total_pages: 728
      order: 1
      base_file: AE74.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
