id: P008138
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4218
  title: གསུང་ཐོར་བུ། དགེ་འདུན་ཆོས་སྐྱོང་རྒྱ་མཚོ
  author: ''
  volumes:
    4201a6f4a2034432aecdd91f81d799f3:
      image_group_id: I1PD97329
      title: ''
      volume_number: 1
      total_pages: 728
ebook_metadata:
  title: གསུང་ཐོར་བུ། དགེ་འདུན་ཆོས་སྐྱོང་རྒྱ་མཚོ
  author: ''
  sku: P008138
  cover: cover.jpg
  layers:
  - pagination
